apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform_jenkinserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: terraform_jenkinserver
  template:
    metadata:
      labels:
        app: terraform_jenkinserver
    spec:
      containers:
      - name: trend-app
        image: mubha/terraform_jenkinserver:latest
        ports:
        - containerPort: 80
