apiVersion: v1
kind: Service
metadata:
  name: terraform_jenkinserver-service
spec:
  type: LoadBalancer
  selector:
    app: terraform_jenkinserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
